spring.config.activate.on-profile: local
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/employees?useSSL=false&allowPublicKeyRetrieval=true&tinyInt1isBit=false
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 15
      leak-detection-threshold: 3000
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate.default_batch_fetch_size: 100

---
spring.config.activate.on-profile: live
