spring.config.activate.on-profile: local

spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate.default_batch_fetch_size: 100

---
spring.config.activate.on-profile: live
